---
title: "Cincinatti311Data"
author: "mspcvsp"
date: "March 27, 2016"
output: html_document
---

```{r setup, include=FALSE}
library("lubridate")
library("ggplot2")
library("scales")
library("reshape")
library("RColorBrewer")
knitr::opts_chunk$set(echo = TRUE)
```

## Monthly Occurrences of Cincinnati 311 Incidents

```{r analyizeMonthlyCount}
monthlyCount <- read.table("../../VMShare/monthly_count.tsv",
                           sep="\t",
                           stringsAsFactors=FALSE)

colnames(monthlyCount) <- c("month", "totalcount")

monthlyCount$month <- ymd(monthlyCount$month)

monthlyCount <- monthlyCount[order(monthlyCount$month),]

monthlyCount$month <- as.Date(monthlyCount$month)

datebreaks <- seq(monthlyCount$month[1],
                  monthlyCount$month[nrow(monthlyCount)],
                  by="4 month")

# Chang, W. R Graphics Cookbook. O'Reilly Media Inc. Sebastopol, CA. 2012.
# http://shop.oreilly.com/product/0636920023135.do 
ggplot(monthlyCount,aes(x=month,y=totalcount)) + 
    geom_line(size=2, colour="steelblue") +
    geom_point(size=2, shape=21, fill="white") + 
    scale_x_date(breaks=datebreaks,
                 labels=date_format("%Y %b")) +
    theme_gray(base_size=10) +
    theme(axis.text.x = element_text(angle=45, hjust=1)) +
    ylab("Total Requests / Month") +
    xlab("Month") +
    ggtitle("City of Cincinnati 311 Open Data") +
    ggsave("./monthlyCounts.png", width=4, height=2.5, dpi=600)
```

## Monthly Occurrences of Cincinnati 311 Service Request Categories
- [Melt function](http://www.r-bloggers.com/melt/)  
- [Rotating x-axis labels](http://stackoverflow.com/questions/1330989/rotating-and-spacing-axis-labels-in-ggplot2)  
- [Expanding ggplot2 color palette](http://novyden.blogspot.com/2013/09/how-to-expand-color-palette-with-ggplot.html)  
```{r analyzeServiceCategoryStats, fig.height=6, fig.width=10}
serviceCategories <- read.csv("../../VMShare/categoryCount.csv",
                              stringsAsFactors=FALSE)

serviceCategories$date <- sub(" 00:00:00", "", serviceCategories$date)

serviceCategories$date <- ymd(serviceCategories$date)

serviceCategories <- melt(serviceCategories,id.vars=c("date"))

colnames(serviceCategories) <- c("date","servicecategory","count")

number_categories <- length(levels(serviceCategories$servicecategory))

getPalette <- colorRampPalette(brewer.pal(8, "Dark2"))

ggplot(serviceCategories, aes(x=date,y=count)) + 
    geom_point(aes(colour=servicecategory)) +
    facet_wrap(~servicecategory, ncol=4) + 
    theme(axis.text.x=element_text(angle = 90)) +
    scale_color_manual(values=getPalette(number_categories)) +
    ggtitle("City of Cincinnati 311 Service Request Category Statistics")
```
